### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by adrianbw** [sekando/feednami-client#3]
Starting some time yesterday, I'm getting a certificate error for api.feednami.com, which stops the feed from loading.

**Comment by richardkazuomiller** [comment]
I'm very sorry about that. This should be fixed now or as soon as the DNS update is propagated. We needed to make a change due to an issue with our hosting provider and when the issue was resolved, we reverted the change we pointed our DNS to a server which was using the wrong certificate for clients in certain regions. Unfortunately, none of our monitoring tools picked up on this issue so thank you very much for reporting it. I'll make sure it doesn't happen again.

**Comment by adrianbw** [comment]
Thank you! I really appreciate the quick fix.
