### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by thomand** [sekando/feednami-client#4]
Hi!

This is probably mentioned in some docs somewhere, but I can't find it. I'm trying to use your library for a norwegian RSS feed. I get the result, but norwegian special characters "æ", "ø" and "å" isn't encoded properly and is replaced by "?". Is there any way to specify encoding in the load function? 

Thanks!

**Comment by richardkazuomiller** [comment]
That's interesting. The backend is supposed to detect the encoding based on the content of the response and its headers. I've tested it with Japanese and some non UTF-8 encodings but not Norwegian. Could you tell me the URL of the feed so I can check it out?

**Comment by thomand** [comment]
The url is 
https://www.retriever-info.com/feed/2002900/generelt43987/aktuelt_-_feed.xml
The same feed is also here (don't know why):
https://www.retriever-info.com/feed/2002900/generelt43987/index.xml

I get the same issue on both. Thanks for checking it out! @richardkazuomiller

**Comment by richardkazuomiller** [comment]
I think the issue should be fixed on the server now. The parser wasn't detecting the encoding when the charset is defined in the processing instructions of the feed in the content of the HTTP response and not in the HTTP headers.

I think I will add an option to specify encoding in the request eventually, but since this fix should work for most feeds that are configured properly and I need to make sure what character sets the API can support, I'm going to leave that as a low priority task for now.

I can't read Norwegian so could you take a look and close the issue if everything looks OK?

**Comment by thomand** [comment]
It works now. Thanks for the quick fix!
